### PR TITLE
EE4J-8

### PR DESCRIPTION
**Pull request by tomjenkinson**
I have created this PR so that all the commits are in one PR as the PR job wants to build the RI and so that requires the GAV to be correct

https://github.com/eclipse-ee4j/jakartaee-tck/pull/9 is the change for the TCK to find the new jar name

### CODE REVIEW

**Comment by anajosep** [comment]
Yes looks like its not able to download the GlassFish Bundle from this location without credentials. For the time being, I ll place it under download.eclipse.org JavaEETCK area as a work around.

[signaturetest/javaee] + wget --progress=bar:force --no-cache https://jenkins.eclipse.org/jta/job/eclipse-ee4j_jta-api-pulls/44/artifact/glassfish/appserver/distributions/glassfish/target/glassfish.zip -O /root/latest-glassfish.zip
[signaturetest/javaee] --2018-10-08 12:22:48--  https://jenkins.eclipse.org/jta/job/eclipse-ee4j_jta-api-pulls/44/artifact/glassfish/appserver/distributions/glassfish/target/glassfish.zip
[signaturetest/javaee] Resolving jenkins.eclipse.org (jenkins.eclipse.org)... 172.30.4.122
[signaturetest/javaee] Connecting to jenkins.eclipse.org (jenkins.eclipse.org)|172.30.4.122|:443... connected.
[signaturetest/javaee] HTTP request sent, awaiting response... 403 Forbidden
[signaturetest/javaee] 2018-10-08 12:22:48 ERROR 403: Forbidden.

> 
> 
> @anajosep looking at https://jenkins.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/61/consoleFull it is failing because the glassfish.zip is on Eclipse CI infrastructure which needs an authenticated user ([signaturetest/javaee] 2018-10-08 12:22:48 ERROR 403: Forbidden)

**Comment by anajosep** [comment]
It does not allow me to download from my browser as well. It fails to download in between.

**Comment by lukasj** [comment]
@anajosep javax.json.jar was renamed javax.json-api.jar

**Comment by anajosep** [comment]
> 
> 
> @anajosep would it be possible to try a run with [eclipse-ee4j/jakartaee-tck#9](https://github.com/eclipse-ee4j/jakartaee-tck/pull/9) please? Assuming that is the right way to fix the JTA related failures?
@tomjenkinson Its the right way to fix it. But unfortunately we are using a prebuilt bundle, I have made a hack in the script to change the jar names. Now the CTS run is clean. The results are available in the below link
https://jenkins.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/64/

**Pull request merged**
