### PR TITLE
1.3.2 release

### PR DESCRIPTION
**Pull request by tomjenkinson**

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
This shall be ignored.

**Comment by Tomas-Kraus** [comment]
@tomjenkinson Why 1.3.3? Last release in central is 1.3.0.

**Comment by Tomas-Kraus** [comment]
[ERROR] Failed to execute goal on project ejb-container: Could not resolve dependencies for project org.glassfish.main.ejb:ejb-container:glassfish-jar:5.0.1-SNAPSHOT: Could not find artifact org.glassfish.metro:webservices-api-osgi:jar:2.4.3 in sonatype-nexus-staging
...this is on our side, metro release failed on some javadoc issue. I'll fix it.

**Comment by Tomas-Kraus** [comment]
I should check some official documents written by Bill and Dmitry to be 100% sure. But what I remember from discussions about versioning, our plan was to release x.y.z from Oracle repositories, move it to Eclipse and release x.y.z+1 from EE4J_8.
The reason for incrementing version above x.y.z+1 in some projects was that people already accidentally released EE4J_8 artifacts into central without GlassFish integration and passing all CTS/TCK tests.

**Comment by Tomas-Kraus** [comment]
OK, if 1.3.2 was already introduced somewhere, you'll probably have to keep it. But it will make additional work to whole integration process - we must update all projects consuming JTA API.
If you just re-publish 1.3.1, all the dependent project will pull new artifact without the need of changing poms.

**Comment by Tomas-Kraus** [comment]
@bshannon @m0mus @romain-grecourt What do you guys think about versions being incremented while still only in OSSRH staging?

**Comment by Tomas-Kraus** [comment]
I got it: https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components
So to meet requirements of this document, you should keep 1.3.1 version in EE4J_8 branch.

**Comment by Tomas-Kraus** [comment]
#27 is there because of EclipseLink integration. EclipseLink uses Eclipse Tycho build and P2 repository which requires Bundle-SymbolicName to match grouId/artifactId as jar file name format.
We need #27 to be part of artifacts integrated into metro/eclipselink/GF/....

**Comment by Tomas-Kraus** [comment]
OK. Let's wait for them to answer.
--
I'm still working on Metro release. Now I got 
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project wsit-tests: Remote staging failed: Failed to deploy metadata: Could not transfer metadata org.glassfish.metro:metro-standalone/maven-metadata.xml from/to ossrh (https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/orgglassfishmetro-1010): oss.sonatype.org: System error: Unknown host oss.sonatype.org: System error -> [Help 1]
after several artifacts had beed successfully uploaded :(

so running it again. We'll see after an hour.

**Comment by Tomas-Kraus** [comment]
@tomjenkinson Metro artifacts are deployed, try to restart build job here

**Comment by romain-grecourt** [comment]
> @bshannon @m0mus @romain-grecourt What do you guys think about versions being incremented while still only in OSSRH staging?

That's fine If these are intermediate builds or if you don't have issues with the version gap. Note that OSSRH has a retention period of 1 month, so advertising artifacts from the staging repository is not practical at all.

Overall, re-releasing a previously released version should be limited to a small set of use-cases.
E.g. the artifacts disappeared because of the retention period, or an API with final version has a bug that needs to be fixed.

**Comment by Tomas-Kraus** [comment]
@romain-grecourt @tomjenkinson  Well so if version will be raised, it should be updated in https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker and all dependent projects must be notified to sync.

**Comment by bshannon** [comment]
Ideally, the 1.3.1 artifacts should've been released to Maven Central when the release review was complete (assuming they passed the TCK, of course).  Then this fix would've appeared in 1.3.2 and there would be no controversy.

Since that wasn't done, we have to evaluate the tradeoff between updating an already staged and approved final release, and leaving a gap in the version numbers.  As Romain says, updating a staged final release is problematic because of the need to flush caches.  I don't think this bug is critical enough that we need to re-stage the final 1.3.1 release.  And changing a release after it was approved in the release review is not something I want to encourage.  So, I'm fine with publishing this as 1.3.2.

**Comment by Tomas-Kraus** [comment]
@tomjenkinson So now we have to resolve one last issue: Build jobs to renew missing artifact in OSSRH staging. Current release job just publishes HEAD of given branch under specified version, but it will not work for JTA API after freezing version. Wee need another one (or parametrize current one) to build it from existing release tag without updating github.
Also, when checking https://oss.sonatype.org/content/groups/staging/jakarta/transaction/jakarta.transaction-api/ there is no 1.3.2 available. So we have 1st test case for such a job. :)

**Comment by Tomas-Kraus** [comment]
...I have some spare time now so I can try to modify JTA API release job this way

**Comment by Tomas-Kraus** [comment]
That job may not work properly if there are multiple deployments with jakartatransaction\-[0-9]+ ID.
After adopting parent 1.0.5,  running `mvn -Poss-release -Pstaging clean deploy` should do the rc-close itself.
Check my modification in eclipse-ee4j_jta-api-EE4J_8-release:
```
# Project identifiers
ARTIFACT_ID=$(mvn -B ${HELP_PLUGIN}:evaluate -Dexpression=project.artifactId | grep -Ev '(^\[)')
GROUP_ID=$(mvn -B ${HELP_PLUGIN}:evaluate -Dexpression=project.groupId | grep -Ev '(^\[)')
STAGING_DESC="${GROUP_ID}:${ARTIFACT_ID}:${RELEASE_VERSION}"
STAGING_KEY=$(echo ${STAGING_DESC} | sed -e 's/\./\\\./g')
...
echo '-[ Drop old staging repository deployments ]------------------------------------'
for staging_key in $(mvn -B nexus-staging:rc-list | egrep "^\[INFO\] [A-Z,a-z,-]+-[0-9]+\s+[A-Z]+\s+${STAGING_KEY}" | awk '{print $2}'); do
  echo "Repository ID: ${staging_key}"
  mvn -U -C -B \
      -DstagingRepositoryId="${staging_key}" \
      nexus-staging::rc-drop
done
echo '-[ Deploy artifacts to staging repository ]-------------------------------------'
mvn -U -C -B \
    -DskipTests -Ddoclint=none -Poss-release,staging \
    -DstagingDescription="${STAGING_DESC}" \
    clean ${MVN_DEPLOY_ARGS}
```
I'm using STAGING_DESC as a key. It's nexus description with groupId:artifactId:version and it's also used to filter and delete old deploymens. Relying on jakartatransaction may not be enough and you may accidentaly delete old deployments of another version.

**Comment by Tomas-Kraus** [comment]
...those disappearing jars are nightmare for whole integration testing. I'm doing nothing than fixing it from the beginning of this week. :(

**Comment by Tomas-Kraus** [comment]
I'll have a look at it. Just need to find some way how to minimize impact on existing artifacts. But Romain still has night so he won't restart GF jobs now.

**Comment by Tomas-Kraus** [comment]
It's done.
Artifacts are there: https://oss.sonatype.org/content/groups/staging/jakarta/transaction/jakarta.transaction-api/
1.3.1 build: https://jenkins.eclipse.org/jta/job/eclipse-ee4j_jta-api-EE4J_8-promote/37/console
1.3.2 build: https://jenkins.eclipse.org/jta/job/eclipse-ee4j_jta-api-EE4J_8-promote/39/console
Nexus staging content: https://jenkins.eclipse.org/jta/job/nexus-staging/10/console to make sure there is no mess left.

Unfortunately 1.3.1 still references to old parent so code is much more complicated than it should be with 1.0.5 only.

**Pull request merged**
